### ISSUE TITLE
trackbar 1.7 easily triggers bug where you cannot scroll down anymore and text is hidden on irssi 0.8.15

### ISSUE THREAD

**Issue by nkuttler** [mjholtkamp/irssi-trackbar#5]
Hi, I'm using Debian Wheezy and after a recent upgrade of trackbar.pl got the effect described in the title. Downgrading to 1.4 again fixed the issue, I never tried another version than 1.4 and 1.7. Please let me know if you need more info.

It was suggested that irssi  0.8.17 could also fix the problem, but I didn't check that.

**Comment by bw1** [comment]
more info :)

output of:
  /scripts
  $ echo $TERM
  $ echo $LANG

terminal emulator?

screenshot

history:
<pre>
 3. 4.2010 Irssi 0.8.15
15. 8.2012 trackbar 1.5
19.11.2013 trackbar 1.7
28. 5.2014 Irssi 0.8.16
</pre>

**Comment by mjholtkamp** [comment]
Hi, could you try again with 1.8?

**Comment by nkuttler** [comment]
Hi, yes the problem still happened with 1.8. But I have tracked down the cause. I was running irssi inside GNU screen, but my TERM variable was set to xterm, not screen (for some historical reason I can't remember). Setting TERM to screen fixes the problem, as does upgrading to irssi 0.8.17. Feel free to close the bux as wontfix because of misconfiguration/user error.

**Comment by mjholtkamp** [comment]
Thanks a lot for your research! I will do as you suggested.
