### ISSUE TITLE
Trackbar 1.8 hides text irssi 0.8.15(In screen)

### ISSUE THREAD

**Issue by Scuzzball** [mjholtkamp/irssi-trackbar#6]
So this is very similar to issue #5, but `TERM` is already set to `screen` in my case.

Some tabs will just not scroll to the bottom, it just says `--more--`.
I can scroll up and back down, but no further down that previously.

When new text has appeared, I can scroll down as many lines as have appeared.

`TERM`: `screen`
`LANG`: `en_US.UTF-8` (I am running screen with the `-U` flag, I had some problem that was fixed by forcing unicode support)
`/script list` output
```
14:38            --- | Script               Path
14:38            --- | screen_away          /home/mtfurlan/.irssi/scripts/autorun/screen_away.pl                                                             
14:38            --- | scriptassist         /home/mtfurlan/.irssi/scripts/autorun/scriptassist.pl                                                            
14:38            --- | nicklist             /home/mtfurlan/.irssi/scripts/autorun/nicklist.pl                                                                
14:38            --- | hilightwin           /home/mtfurlan/.irssi/scripts/autorun/hilightwin.pl                                                              
14:38            --- | trackbar             /home/mtfurlan/.irssi/scripts/trackbar.pl                                                                        
14:38            --- | xchatnickcolor       /home/mtfurlan/.irssi/scripts/xchatnickcolor.pl
```

Screenshot is of the status tab:
![Screenshot](http://i.imgur.com/3BEytWk.png)

**Comment by ailin-nemui** [comment]
do not use these trackbar versions on irssi 0.8.15

**Comment by Scuzzball** [comment]
Which version should I use? Should I upgrade or downgrade?

**Comment by ailin-nemui** [comment]
upgrade irssi ;-) or use the original versions 1.4 or 2.2

**Comment by Scuzzball** [comment]
So I'm having *great* fun compiling irssi locally(without root), so on the assumption that I don't succeed, is [this](http://anti.teamidiot.de/static/nei/*/Code/Irssi/trackbar22.pl) what you mean by version 2.2? Only relevant result from googling "irssi trackbar 2.2"
I found [1.4](https://people.mozilla.org/~gavin/irssi/scripts/trackbar.pl) a bit easier, but the 2.2 seems more feature rich.

Would you mind mentioning in the readme the version requirements, just to help future people?

**Comment by Scuzzball** [comment]
I finally got irssi to compile, and trackbar seems to work on current irssi. I'll close it, but if you could add the version requirement to the readme that would be nice.
