### ISSUE TITLE
Feature request: Don't show a trackbar on the bottom of the windows.

### ISSUE THREAD

**Issue by CamilleScholtz** [mjholtkamp/irssi-trackbar#8]
This means no one has said something anyways. screenshot of what I mean: https://punpun.xyz/37ee.png

**Comment by mjholtkamp** [comment]
Sorry, I'm not going to develop that. Sadly I'm not using irssi anymore so It's too much hassle to develop if I can't even test it myself. I think my project has been forked a couple of times, maybe you can find another one that has more active developers.
